{ 
 id: MessageId(10),
 date: "2022-11-19T15:27:00Z",
 chat: Chat { id: ChatId(-818700708),
 kind: Public(ChatPublic { title: Some("S*cr*ts"),
 kind: Group(PublicChatGroup { permissions: None }),
 description: None,
 invite_link: None,
 has_protected_content: None }),
 photo: None,
 pinned_message: None,
 message_auto_delete_time: None },
 via_bot: None,
 kind: Common(MessageCommon { from: Some(User { id: UserId(887728385),
 is_bot: false,
 first_name: "Evgeny",
 last_name: Some("Roskach"),
 username: Some("genyrosk"),
 language_code: Some("en"),
 is_premium: false,
 added_to_attachment_menu: false }),
 sender_chat: None,
 author_signature: None,
 forward: None,
 reply_to_message: None,
 edit_date: None,
 media_kind: Text(MediaText { text: "/start",
 entities: [MessageEntity { kind: BotCommand,
 offset: 0,
 length: 6 }] }),
 reply_markup: None,
 is_automatic_forward: false,
 has_protected_content: false })
}
